apiVersion: v1
kind: Service
metadata:
  name: {{ include "afs.afsletHeadlessServiceName" . }}
  labels:
    {{- include "afs.labels" . | nindent 4 }}
    app.kubernetes.io/component: afslet
spec:
  clusterIP: None
  selector:
    {{- include "afs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: afslet
  ports:
    - name: grpc
      port: {{ .Values.afslet.service.port }}
      targetPort: grpc
      protocol: TCP
