apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "afs.discoveryServiceName" . }}
  labels:
    {{- include "afs.labels" . | nindent 4 }}
    app.kubernetes.io/component: discovery
spec:
  replicas: {{ .Values.discovery.replicas }}
  selector:
    matchLabels:
      {{- include "afs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: discovery
  template:
    metadata:
      labels:
        {{- include "afs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: discovery
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: discovery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -listen=:{{ .Values.discovery.containerPort }}
          command:
            - /usr/local/bin/afs_discovery_grpcd
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  containerName: discovery
                  resource: limits.cpu
                  divisor: "1"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: discovery
                  resource: limits.memory
                  divisor: "1"
          ports:
            - name: grpc
              containerPort: {{ .Values.discovery.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.discovery.resources | nindent 12 }}
