apiVersion: v1
kind: Service
metadata:
  name: {{ include "afs.discoveryServiceName" . }}
  labels:
    {{- include "afs.labels" . | nindent 4 }}
    app.kubernetes.io/component: discovery
spec:
  type: {{ .Values.discovery.service.type }}
  selector:
    {{- include "afs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: discovery
  ports:
    - name: grpc
      port: {{ .Values.discovery.service.port }}
      targetPort: grpc
      protocol: TCP
